### ISSUE TITLE
Failures in a file included with `@includeRmd` will nuke the NAMESPACE

### ISSUE THREAD

**Issue by DavisVaughan** [r-lib/roxygen2#1254] opened 2021-10-01 17:13 UTC
If you include a file with `@includeRmd` that fails during `roxygenise()`, then your NAMESPACE will be (mostly) nuked, which often puts you in a state where you can't even `roxygenise()` again to fix it. You end up having to revert the changes made to the NAMESPACE manually, fix the Rmd (or whatever made it fail), and then redocument. (This has bitten the tidymodels team, and me in vctrs quite a few times)

I have a somewhat minimal example here, where this commit changed an Rmd to make it fail, I redocumented, and now the exported function `fn()` is no longer part of NAMESPACE
https://github.com/DavisVaughan/testfailingroxygen2/commit/ad6f49fd34073758c9d69fb88089673051f920e1

The way this occurs is:
- [`roclet_preprocess()`](https://github.com/r-lib/roxygen2/blob/6c1e42f061e9435a14bd3a0e01c7f08fc7aa9160/R/roxygenize.R#L73) has a namespace method that inserts partial information into the NAMESPACE file. It seems to insert information about imports only.
- [`roclet_process()`](https://github.com/r-lib/roxygen2/blob/6c1e42f061e9435a14bd3a0e01c7f08fc7aa9160/R/roxygenize.R#L80) will then run, and the Rd method for that is where the Rmd is rendered and subsequently fails.
- [`roclet_output()`](https://github.com/r-lib/roxygen2/blob/6c1e42f061e9435a14bd3a0e01c7f08fc7aa9160/R/roxygenize.R#L88) never gets to run, which is where the NAMESPACE is finalized, so we end up with the broken partial NAMESPACE that `roclet_preprocess()` wrote.

I see two potential solutions:
- `roxy_tag_rd.roxy_tag_includeRmd()` could `tryCatch()` the `rmarkdown::render()` call? Or maybe pass something to `render()` to make it not fail.
- More generally, I'm not entirely sure why `roclet_preprocess.roclet_namespace()` exists. It seems like the process and output methods for roclet_namespace will basically do the same thing, just with `import_only = FALSE`. If the preprocess method wasn't run, it seems like we wouldn't get into that problematic state from above because we would never write a partial NAMESPACE to disk. I'm probably missing something though https://github.com/r-lib/roxygen2/blob/6c1e42f061e9435a14bd3a0e01c7f08fc7aa9160/R/namespace.R#L34-L63.

**Comment by gaborcsardi** [comment] 2021-10-01 17:45
This does not happen to me, am I doing this right?

```
~/works/testfailingroxygen2 main
❯ cat NAMESPACE
# Generated by roxygen2: do not edit by hand

import(rlang)
```

```
~/works/testfailingroxygen2 main
❯ R -q -e 'packageVersion("roxygen2")'
> packageVersion("roxygen2")
[1] ‘7.1.2’
>
>
```

```
~/works/testfailingroxygen2 main
❯ R -q -e 'devtools::document()'
> devtools::document()
ℹ Updating testfailingroxygen2 documentation
ℹ Loading testfailingroxygen2
Quitting from lines 13-14 (/Users/gaborcsardi/works/testfailingroxygen2/man/rmd/test.Rmd)
Quitting from lines 2-5 (/Users/gaborcsardi/works/testfailingroxygen2/man/rmd/test.Rmd)
Error in eval(expr, envir, enclos) : oh no
Calls: <Anonymous> ... handle -> withCallingHandlers -> withVisible -> eval -> eval
Execution halted
```

```
~/works/testfailingroxygen2 main
❯ cat NAMESPACE
# Generated by roxygen2: do not edit by hand

import(rlang)
```

**Comment by DavisVaughan** [comment] 2021-10-01 17:49
If you change the `stop("oh no")` to something that doesn't error and redocument, you should get a `export(foo)` put back in the NAMESPACE. Then you should be back in a "correct" state.

So then you can add `stop("oh no")` back in and see that when you redocument, it should remove that `export(foo)` again, which is the problem.

---

I committed all the changes that roxygen2 made, which was probably confusing

**Comment by gaborcsardi** [comment] 2021-10-01 18:02
Got it. Two workarounds, that are IMO better than `@includeRmd` anyway:

1. If you only need the code chunk once, then include it directly in the R file:
   ````
   #' ```{r, error = FALSE}
   #' stop("oh no")
   #' ```
   ````

2. If you need it in multiple files, then use child documents:
   ````
   #' ```{r, child = "man/rmd/test.Rmd", error = FALSE}
   #' ```
   ````

**Comment by DavisVaughan** [comment] 2021-10-19 14:28
Just want to clarify that the errors are unexpected, i.e. I would never set `error = FALSE` before running the entire Rmd. I don't expect any errors and would like to be notified if any errors occur. I just don't want it to nuke the NAMESPACE file in the process

**Comment by hadley** [comment] 2021-11-15 19:45
Maybe the `NAMESPACE` that just records the imports could also include the standard export pattern thing, so if the second step fails at least you're not completely hosed?

Or maybe we should have some way to roll back to the previous namespace if the whole process fails?

**Comment by hadley** [comment] 2022-03-29 18:58
Possible duplicate of #1144

**Comment by hadley** [comment] 2022-03-31 16:02
This approach seems promising: 

```R
library(tidyverse)

parsed <- parse("NAMESPACE", keep.source = TRUE)
is_import <- function(x) is_call(x, c("import", "importFrom", "importClassesFrom", "importMethodsFrom"))
unlist(lapply(attr(parsed, "srcref")[!vapply(parsed, is_import, logical(1))], as.character))
```

**Comment by DavisVaughan** [comment] 2022-03-31 16:26
Yea, I think the super broken state is related to S3 methods.

I have created an updated `"broken"` branch in that repo. You can check it out or do `usethis::pr_fetch(1)` to get it.

1. Open `man/rmd/test.Rmd`
2. Run CMD+SHIFT+D to document, note that everything is working
3. Uncomment the `stop()`
4. Document again, it should fail - It nukes `NAMESPACE`
5. Comment the `stop()` out
6. Document again, it should _still_ fail - it complains about not being able to find an S3 method for `"double"`

**Comment by hadley** [comment] 2022-03-31 17:18
Ah of course, because you're using an exported function that's no longer exported.

**Closed** 2022-04-01 19:54 UTC
Labels: bug, namespace :woman_astronaut:
