### ISSUE TITLE
Warning: Dropping empty section \value 

### ISSUE THREAD

**Issue by jcubic** [r-lib/roxygen2#1068] opened 2020-03-23 14:56 UTC
I have function documentation and `@return` is ignored
```
#' Basic function to create battery components.
#'
#' @description
#' Use this function to create new battery class object.
#'
#' @return Object of \code{\link{R6Class}}, with battery specific methods (see \code[\link{BaseComponent}})
#' @param classname - name of the class as string
#' @param public - list of public functions and properties
#' @param private - list of private functions and properties
#' @param static - list of fields that will stay the same for every instance of the component
#' @param inherit - base class - if not specifed it will inherit from Base class \code{\link{BaseComponent}}
#' @param ... - reset option passed to \code{\link{R6Class}} constructor
#' @export
#' @examples
#' ...
component <- function(classname,
                      public = NULL,
                      private = NULL,
                      static = NULL,
                      inherit = battery:::BaseComponent,
                      ...) {
}
```

**Comment by gaborcsardi** [comment] 2020-03-23 15:00
Can you please try to create a reproducible example as per https://github.com/r-lib/roxygen2/blob/master/.github/SUPPORT.md#making-a-reprex ? Thanks.

**Comment by jcubic** [comment] 2020-03-23 15:10
This warning is not from roxygen it's from devtools check but roxygen is droping broken code in `@return` without giving any warning or error.

This was my code:
```R
#' @return Object of \code{\link{R6Class}}, with battery specific methods (see \code[\link{BaseComponent}})
```
and it should be:
```R
#' @return Object of \code{\link{R6Class}}, with battery specific methods (see \code{\link{BaseComponent}})
```
second \code had open bracket instead of open curly brace.

**Comment by hadley** [comment] 2020-05-01 15:36
``` r
library(roxygen2)
out1 <- roc_proc_text(rd_roclet(), "
  #' Title
  #'
  #' @return \\code[\\link{BaseComponent}})
  #' @md
  foo <- function() {}")[[1]]

out1 <- roc_proc_text(rd_roclet(), "
  #' Title
  #'
  #' @return \\code[\\link{BaseComponent}})
  foo <- function() {}")[[1]]
#> Warning: [<text>:4] @return mismatched braces or quotes
```

<sup>Created on 2020-05-01 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Looks like the markdown path is missing a call to `rdComplete()`? Maybe before we do anything to the markdown?

**Comment by hadley** [comment] 2022-07-08 19:43
Duplicate of #1340

**Closed by hadley** 2022-07-08 19:43 UTC
Labels: bug, markdown :arrow_down:
