### ISSUE TITLE
Inheriting params with "modernized" lifecycle badge usage produces invalid Rd markup

### ISSUE THREAD

**Issue by cjyetman** [r-lib/roxygen2#1292] opened 2022-02-20 13:51 UTC
In `{readr}` version 2.1.2 the lifecycle badge usage was "modernized" with [this commit](https://github.com/tidyverse/readr/commit/b99af3399093a3e0296667ab49e192697fb9dbba#). Now when inheriting params from `readr::write_csv`, the Rd markup generated for the `path` and `quote_escape` parameters are invalid (i.e. cause warnings in R CMD check).

For reasons I do not understand, the Rd markup generated for/in `{readr}` is different (and presumably valid) than what is generated when I import those parameters.

from `{readr}` ([link](https://github.com/tidyverse/readr/blob/b99af3399093a3e0296667ab49e192697fb9dbba/man/write_delim.Rd#L151-L155))
```
\item{path}{\ifelse{html}{\href{https://lifecycle.r-lib.org/articles/stages.html#deprecated}{\figure{lifecycle-deprecated.svg}{options: alt='[Deprecated]'}}}{\strong{[Deprecated]}} Use the \code{file} argument
instead.}

\item{quote_escape}{\ifelse{html}{\href{https://lifecycle.r-lib.org/articles/stages.html#deprecated}{\figure{lifecycle-deprecated.svg}{options: alt='[Deprecated]'}}}{\strong{[Deprecated]}} Use the \code{escape}
argument instead.}
```

generated using `@inheritDotParams`
```
\item{\code{path}}{\ifelse{{html}{\href{https://lifecycle.r-lib.org/articles/stages.html#deprecated}{\figure{lifecycle-deprecated.svg}{options: alt='[Deprecated]'}}}{\strong{[Deprecated]}}} Use the \code{file} argument
instead.}

\item{\code{quote_escape}}{\ifelse{{html}{\href{https://lifecycle.r-lib.org/articles/stages.html#deprecated}{\figure{lifecycle-deprecated.svg}{options: alt='[Deprecated]'}}}{\strong{[Deprecated]}}} Use the \code{escape}
argument instead.}
```

reproducible example...
``` r
library(roxygen2)
packageVersion("roxygen2")
#> [1] '7.1.2'
packageVersion("readr")
#> [1] '2.1.2'
roc_proc_text(rd_roclet(), "
  #' Title
  #' @inheritDotParams readr::write_csv
  #'
  #' @export
  foo <- function(x, file, ...) {}
")
#> $foo.Rd
#> % Generated by roxygen2: do not edit by hand
#> % Please edit documentation in ./<text>
#> \name{foo}
#> \alias{foo}
#> \title{Title}
#> \usage{
#> foo(x, file, ...)
#> }
#> \arguments{
#> \item{...}{
#>   Arguments passed on to \code{\link[readr:write_delim]{readr::write_csv}}
#>   \describe{
#>     \item{\code{x}}{A data frame or tibble to write to disk.}
#>     \item{\code{file}}{File or connection to write to.}
#>     \item{\code{na}}{String used for missing values. Defaults to NA. Missing values
#> will never be quoted; strings with the same value as \code{na} will
#> always be quoted.}
#>     \item{\code{append}}{If \code{FALSE}, will overwrite existing file. If \code{TRUE},
#> will append to existing file. In both cases, if the file does not exist a new
#> file is created.}
#>     \item{\code{col_names}}{If \code{FALSE}, column names will not be included at the top of the file. If \code{TRUE},
#> column names will be included. If not specified, \code{col_names} will take the opposite value given to \code{append}.}
#>     \item{\code{quote}}{How to handle fields which contain characters that need to be quoted.
#> \itemize{
#> \item \code{needed} - Only quote fields which need them.
#> \item \code{all} - Quote all fields.
#> \item \code{none} - Never quote fields.
#> }}
#>     \item{\code{escape}}{The type of escape to use when quotes are in the data.
#> \itemize{
#> \item \code{double} - quotes are escaped by doubling them.
#> \item \code{backslash} - quotes are escaped by a preceding backslash.
#> \item \code{none} - quotes are not escaped.
#> }}
#>     \item{\code{eol}}{The end of line character to use. Most commonly either \code{"\n"} for
#> Unix style newlines, or \code{"\r\n"} for Windows style newlines.}
#>     \item{\code{num_threads}}{Number of threads to use when reading and materializing
#> vectors. If your data contains newlines within fields the parser will
#> automatically be forced to use a single thread only.}
#>     \item{\code{progress}}{Display a progress bar? By default it will only display
#> in an interactive session and not while knitting a document. The display
#> is updated every 50,000 values and will only display if estimated reading
#> time is 5 seconds or more. The automatic progress bar can be disabled by
#> setting option \code{readr.show_progress} to \code{FALSE}.}
#>     \item{\code{path}}{\ifelse{{html}{\href{https://lifecycle.r-lib.org/articles/stages.html#deprecated}{\figure{lifecycle-deprecated.svg}{options: alt='[Deprecated]'}}}{\strong{[Deprecated]}}} Use the \code{file} argument
#> instead.}
#>     \item{\code{quote_escape}}{\ifelse{{html}{\href{https://lifecycle.r-lib.org/articles/stages.html#deprecated}{\figure{lifecycle-deprecated.svg}{options: alt='[Deprecated]'}}}{\strong{[Deprecated]}}} Use the \code{escape}
#> argument instead.}
#>   }}
#> }
#> \description{
#> Title
#> }
```

<sup>Created on 2022-02-20 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

results in warnings from R CMD check
```
prepare_Rd: bad markup (extra space?) at write_csv_file.Rd:49:194
prepare_Rd: man/write_csv_file.Rd:49: unexpected macro '\code', expecting TEXT or '{'
prepare_Rd: bad markup (extra space?) at write_csv_file.Rd:51:202
prepare_Rd: man/write_csv_file.Rd:51: unexpected macro '\code', expecting TEXT or '{'
```

**Comment by hadley** [comment] 2022-03-29 19:02
Probably duplicate of #1062

**Comment by cjyetman** [comment] 2022-03-30 07:41
confirmed: 2f5079a1ec465fd8c7fa52b7a6651045c7772dd8 resolves both the issue in my test case here, and the original issue that prompted this issue

**Comment by hadley** [comment] 2022-03-30 12:38
Great, thanks for checking!

**Closed by hadley** 2022-03-30 12:38 UTC
Labels: bug, inherit :family_man_woman_girl_boy:
