### ISSUE TITLE
Reexports - Package links

### ISSUE THREAD

**Issue by JohnCoene** [r-lib/roxygen2#1111] opened 2020-06-12 09:47 UTC
CRAN checks fails on Debian, raising the warning below

```
* checking Rd cross-references ... WARNING
Non-file package-anchored link(s) in documentation object 'reexports.Rd':
  ‘[htmltools]{tags}’
```

This is caused by the following

```r
#' @importFrom htmltools tags
#' @export
htmltools::tags
```

which generates `reexports.Rd`

````
% Generated by roxygen2: do not edit by hand
% Please edit documentation in R/pipe.R
\docType{import}
\name{reexports}
\alias{reexports}
\alias{tags}
\title{Objects exported from other packages}
\keyword{internal}
\description{
These objects are imported from other packages. Follow the links
below to see their documentation.

\describe{
  \item{htmltools}{\code{\link[htmltools]{tags}}}
}}
````

While there is a fix in https://github.com/r-lib/roxygen2/issues/707#issuecomment-520130605 I'm unsure how to apply it to the above as the `\describe` tag is generated by:

https://github.com/r-lib/roxygen2/blob/d148c8415b2a19879eca2c02b660e1884c7c9f00/R/object-import.R#L22

**Comment by gaborcsardi** [comment] 2020-06-12 09:50
Duplicate of #1108 I believe.

**Closed by gaborcsardi** 2020-06-12 09:50 UTC
