### ISSUE TITLE
@describeIn fails when used on S3 method and other funs together

### ISSUE THREAD

**Issue by maxheld83** [r-lib/roxygen2#1181] opened 2021-01-11 21:26 UTC
This was already partially addressed #666. (It was probably only partially addressed because I had failed to provide a reprex).

As per #666 and the below test, you *can* now document other functions via `@describeIn` for generics:

https://github.com/r-lib/roxygen2/blob/b3053b694399416543af877837efb29e6ec34d1f/tests/testthat/test-rd-describe-in.R#L72-L82

However, this fallback isn't triggered when you `@describeIn` methods and other functions together:

```r
library(roxygen2)

  out <- roc_proc_text(rd_roclet(), "
  #' Generic
  # foo <- function(x) {}
  foo <- function(x) UseMethod('foo')

  #' @describeIn foo some method
  as.character.zap <- function(x) c('zap')
  
  #' @describeIn foo related function
  bar <- function(y) {}
")[[1]]
```

yields:

```
Error in merge.rd_section_minidesc(self$get_section(type), section) : 
  identical(x$value$type, y$value$type) is not TRUE
```

Whether the "parent" function (the function you're `@describeIn` *in*) is a normal function or a generic does not seem to matter.
You can trigger the same error with:

```r
library(roxygen2)

  out <- roc_proc_text(rd_roclet(), "
  #' Normal
  foo <- function(x) {}

  #' @describeIn foo some method
  as.character.zap <- function(x) c('zap')
  
  #' @describeIn foo related function
  bar <- function(y) {}
")[[1]]
```

---

#### Motivation

I think this scenario might sometimes happen when documenting new (S3) OO schemes.
For example, you might have a class, and wish to document some (say, print) methods with it, as well as some "normal" functions, such as a validator.

#### More Background

(Not necessary to debug this, but might be helpful to other people who run into this and are confused about the relationship to `vctrs::s3_register()`

You can also run into this problem if you wish to expand other generics (say, `knitr::knit_print()`, which you don't want to `@ImportFrom` (and therefore `Imports:` in your `DESCRIPTION`).
If you then place knitr in your `Suggests:` and dynamically `vctrs::s3_register()` `knit_print` in your `onLoad`, your newly minted method `knit_print.foo()` will then look (to roxygen anyway) as a *normal* function, and will therefore trigger the above error.

**Comment by maxheld83** [comment] 2021-01-22 17:38
this is addressed in #1182

**Comment by gregorgorjanc** [comment] 2021-12-20 22:25
I can report that this tripped me over, and took a long time to figure out what is the issue! It would be great if we could combine multiple types of functions into one Rd file.

**Comment by hadley** [comment] 2022-07-10 22:52
This now gives 

``` r
library(roxygen2)

  out <- roc_proc_text(rd_roclet(), "
  #' Normal
  foo <- function(x) {}

  #' @describeIn foo some method
  as.character.zap <- function(x) c('zap')
  
  #' @describeIn foo related function
  bar <- function(y) {}
")[[1]]
#> Warning: [<text>:9] Don't know how to combine @describeIn types "class" and
#> "function"
```

<sup>Created on 2022-07-10 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

And is a duplicate of #1370

**Closed by hadley** 2022-07-10 22:52 UTC
Labels: feature, rd :writing_hand:
