### ISSUE TITLE
Undocumented code objects for @keywords internal

### ISSUE THREAD

**Issue by simonsays1980** [r-lib/roxygen2#1266] opened 2021-10-30 10:22 UTC
Hi everyone, 

I am working for a time now on the documentation of a large package I wrote. I am struggling with a certain issue: 

I document my setters and getters in the class documentations and put them into *stealth mode* for users by using `@keywords internal` I always receive `Undocumented code objects`  when running `devtools::check()`. 

The documentation of an example getter looks like this: 

```
#' Getter method of `csdatamoments` class.
#' 
#' @description
#' Returns the `B` slot.
#' 
#' @param object An `csdatamoments` object.
#' @return The `B` slot of the `object`.
#' @exportMethod getB
#' @keywords internal
setMethod(
  "getB", "csdatamoments",
  function(object) {
    return(object@B)
  }
)
```
The generic is documented as follows: 
```
#' @export
#' @docType methods
#' @keywords internal
#' @aliases getB,csdatamoments-class
setGeneric("getB", function(object) standardGeneric("getB"))
```
I searched a lot on stackoverflow, but did not find an answer to this question I have. What is my error here? 

Any help is welcome.

**Comment by gaborcsardi** [comment] 2021-10-30 10:59
Can you show us your package?

**Comment by simonsays1980** [comment] 2021-10-30 11:30
Hi @gaborcsardi , 

thanks for coming back to this so quickly. Here is the [link to my package](https://github.com/simonsays1980/finmix/tree/documentation) (use the `documentation` branch.

**Comment by gaborcsardi** [comment] 2021-10-30 11:51
That is a giant package indeed. Do you think you could create a small package that illustrates the problem?

**Comment by gaborcsardi** [comment] 2021-10-30 11:58
I think this is not caused by `@keywords internal`, but you simply need to document the generics you create, in addition to documenting the methods. If I remove all `@keywords internal` tags from your package then I still get the same `Undocumented code objects` warnings from `R CMD check`.

**Comment by simonsays1980** [comment] 2021-10-30 15:29
> That is a giant package indeed. Do you think you could create a small package that illustrates the problem?

I hope I can somehow replicate the problem I have there ...

**Comment by simonsays1980** [comment] 2021-10-30 15:30
> I think this is not caused by `@keywords internal`, but you simply need to document the generics you create, in addition to documenting the methods. If I remove all `@keywords internal` tags from your package then I still get the same `Undocumented code objects` warnings from `R CMD check`.

Thanks for having tested this. By documenting you mean with a `@description`, `@param` and `@returns`?

**Comment by gaborcsardi** [comment] 2021-10-30 15:33
Maybe you just need to remove the commas from your `@aliases` tags? E.g. https://github.com/simonsays1980/finmix/blob/documentation/R/AllGenerics.R#L188
`@aliases` tags are space separated: https://roxygen2.r-lib.org/articles/rd.html#indexing

**Comment by simonsays1980** [comment] 2021-10-30 16:35
> Maybe you just need to remove the commas from your `@aliases` tags? E.g. https://github.com/simonsays1980/finmix/blob/documentation/R/AllGenerics.R#L188 `@aliases` tags are space separated: https://roxygen2.r-lib.org/articles/rd.html#indexing

@gaborcsardi thanks for coming back to this. I tried this out, but had no success. I thought that it needs probably `@aliases` because the generic cannot be connected to the methods bases on itself, but it appears the error I make lays somewhere else.

**Comment by gaborcsardi** [comment] 2021-10-30 18:22
Removing the aliases from the `getB` generic and adding a title, so that roxygen2 can create a man page, eliminates the warning for `getB`: https://github.com/gaborcsardi/finmix/commit/d3f960b7af1dfef934a9f8a433224e150dab3e7e

I am going to close this, because it is surely not an issue with `@keywords internal` and I doubt that it is an issue with roxygen2. You need to document all generics of the package to eliminate these warnings. I.e. you need to have a manual page (or alias) to `getB`, etc.

**Closed** 2021-10-30 18:22 UTC
Labels: reprex

**Comment by simonsays1980** [comment] 2021-10-30 18:33
> Removing the aliases from the `getB` generic and adding a title, so that roxygen2 can create a man page, eliminates the warning for `getB`: [gaborcsardi/finmix@d3f960b](https://github.com/gaborcsardi/finmix/commit/d3f960b7af1dfef934a9f8a433224e150dab3e7e)
> 
> I am going to close this, because it is surely not an issue with `@keywords internal` and I doubt that it is an issue with roxygen2. You need to document all generics of the package to eliminate these warnings. I.e. you need to have a manual page (or alias) to `getB`, etc.

@gaborcsardi thank you very much for the solution to my problem. At some point I couldn't see anymore the cause for the behavior I observed. This solved the issue I had. 

Regarding the `@aliases`: So the aliases on the generic were not sufficient? My thought was: if no documentation for the generic exists it needs another documentation (maybe that of a class where it is used). This did not work. So, it needs the aliases also in the method documentations? This is where I could not get clarity. 

Sure, closing the issue makes totally sense here - thanks for taking the efforts!

**Comment by gaborcsardi** [comment] 2021-10-30 18:40
First, as I noted above, in roxygen2 aliases are space separated, so separating them with a comma was probably a mistake
```r
#' @aliases getB,cmodelmoments-class,exponentialmodelmoments-class
setGeneric("getB", function(object) standardGeneric("getB"))
```
and you wanted to write the following instead?
```r
#' @aliases getB cmodelmoments-class exponentialmodelmoments-class
setGeneric("getB", function(object) standardGeneric("getB"))
```

But this is actually unneeded/incorrect. An alias is an alternative name of a manual page. This manual page will be called `getB`, so there is no need for the `getB` alias. 

The class aliases are incorrect because you already have manual pages called `cmodelmoments-class` and `exponentialmodelmoments-class` and the aliases must be unique within the package. I.e. when you type 
```r
?"exponentialmodelmoments-class"
```
in R, there should be a single manual page to show.

If you just want to link to `exponentialmodelmoments-class` etc. from the `getB` manual page, then you can add links like the ones I added:
```
#' @seealso [cmodelmoments-class], [exponentialmodelmoments-class]
```

**Comment by simonsays1980** [comment] 2021-10-30 18:46
@gaborcsardi thank you very much for clarifying the `@aliases` use to me. That helps. I will now document the generics with a `@title` and keep these documentations internal such that developers can find them if needed and users can see the methods int he class documentation.
