### ISSUE TITLE
@encoding does not apply on @examples block

### ISSUE THREAD

**Issue by nouvrita** [r-lib/roxygen2#1083] opened 2020-04-27 14:50 UTC
Hi,

I'm trying to write documentation for a french package.
In examples, I need to use non-ASCII character such as `é`.
It seems that the tag `@encoding UTF-8` does not work for `@examples` block.

Here is a MWE :
```
library(roxygen2)

doc <- "#' @encoding UTF-8
#' @title é
#' @examples
#' é
foo <- function(){}"

roc_proc_text(rd_roclet(), doc)
```
Output :
```
$foo.Rd
% Generated by roxygen2: do not edit by hand
% Please edit documentation in ./<text>
\encoding{UTF-8}
\name{foo}
\alias{foo}
\title{é}
\usage{
foo()
}
\description{
é
}
\examples{
Ã©
}
```
Version :
```
> packageVersion('roxygen2')
[1] ‘7.1.0.9000’
````
System info :
```
> sessionInfo()
R version 3.6.3 (2020-02-29)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 17763)

Matrix products: default

locale:
[1] LC_COLLATE=French_France.1252  LC_CTYPE=French_France.1252    LC_MONETARY=French_France.1252
[4] LC_NUMERIC=C                   LC_TIME=French_France.1252
```

**Comment by hadley** [comment] 2020-05-01 15:22
Duplicate of #1066 (but not that `@encoding` doesn't do anything here as roxygen2 always assumes utf8 text).

**Closed by hadley** 2020-05-01 15:22 UTC
