### ISSUE TITLE
error in 

### ISSUE THREAD

**Issue by vivekbhr** [r-lib/roxygen2#850] opened 2019-03-06 09:20 UTC
Hi

I am getting 2 issues with my recent `devtools::document()` call on my bioconductor package : https://github.com/vivekbhr/icetea

```
Warning in structure(x, class = "rd") :
  Calling 'structure(NULL, *)' is deprecated, as NULL cannot have attributes.
  Consider 'structure(list(), *)' instead.

Error in wrapString(x, width = as.integer(width)) : 
  Expecting a single string value: [type=list; extent=0].
Calls: <Anonymous> ... topic_add_usage -> wrap_string -> wrap_string.default -> wrapString
Execution halted
```
It seems that the new `topic_add_usage()` function is not able to work properly on my code. Please help me resolve the issue.

Sessioninfo is attached below: 

```
R version 3.5.2 (2018-12-20)
Platform: x86_64-redhat-linux-gnu (64-bit)
Running under: CentOS Linux 7 (Core)

Matrix products: default
BLAS: /package/R-3.5.2/lib64/R/lib/libRblas.so
LAPACK: /package/R-3.5.2/lib64/R/lib/libRlapack.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=C              
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8    LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] icetea_0.99.10

loaded via a namespace (and not attached):
  [1] colorspace_1.3-2                          hwriter_1.3.2                            
  [3] rprojroot_1.3-2                           htmlTable_1.12                           
  [5] XVector_0.20.0                            GenomicRanges_1.32.7                     
  [7] base64enc_0.1-3                           fs_1.2.6                                 
  [9] rstudioapi_0.7                            roxygen2_6.1.1                           
 [11] remotes_2.0.2                             bit64_0.9-7                              
 [13] AnnotationDbi_1.42.1                      xml2_1.2.0                               
 [15] splines_3.5.2                             geneplotter_1.58.0                       
 [17] knitr_1.20                                pkgload_1.0.2                            
 [19] Formula_1.2-3                             Rsamtools_1.32.3                         
 [21] annotate_1.58.0                           cluster_2.0.7-1                          
 [23] compiler_3.5.2                            httr_1.3.1                               
 [25] backports_1.1.2                           assertthat_0.2.0                         
 [27] Matrix_1.2-15                             lazyeval_0.2.1                           
 [29] limma_3.36.2                              cli_1.0.0                                
 [31] acepack_1.4.1                             htmltools_0.3.6                          
 [33] prettyunits_1.0.2                         tools_3.5.2                              
 [35] bindrcpp_0.2.2                            gtable_0.2.0                             
 [37] glue_1.3.0                                GenomeInfoDbData_1.1.0                   
 [39] dplyr_0.7.6                               ShortRead_1.38.0                         
 [41] Rcpp_0.12.18                              Biobase_2.40.0                           
 [43] Biostrings_2.48.0                         rtracklayer_1.40.6                       
 [45] stringr_1.3.1                             ps_1.3.0                                 
 [47] testthat_2.0.0                            devtools_2.0.1                           
 [49] XML_3.98-1.16                             edgeR_3.22.3                             
 [51] zlibbioc_1.26.0                           scales_0.5.0                             
 [53] BSgenome_1.48.0                           VariantAnnotation_1.27.0                 
 [55] hms_0.4.2                                 parallel_3.5.2                           
 [57] SummarizedExperiment_1.10.1               RColorBrewer_1.1-2                       
 [59] yaml_2.2.0                                memoise_1.1.0                            
 [61] gridExtra_2.3                             ggplot2_3.0.0                            
 [63] biomaRt_2.36.1                            rpart_4.1-13                             
 [65] latticeExtra_0.6-28                       stringi_1.2.2                            
 [67] RSQLite_2.1.1                             genefilter_1.62.0                        
 [69] Rhtslib_1.12.0                            S4Vectors_0.18.2                         
 [71] desc_1.2.0                                checkmate_1.8.5                          
 [73] GenomicFeatures_1.32.3                    BiocGenerics_0.26.0                      
 [75] pkgbuild_1.0.2                            BiocParallel_1.15.15                     
 [77] GenomeInfoDb_1.16.0                       rlang_0.2.2                              
 [79] pkgconfig_2.0.2                           commonmark_1.5                           
 [81] matrixStats_0.53.1                        bitops_1.0-6                             
 [83] lattice_0.20-38                           purrr_0.2.5                              
 [85] bindr_0.1.1                               GenomicAlignments_1.16.0                 
 [87] htmlwidgets_1.3                           bit_1.1-13                               
 [89] processx_3.2.1                            tidyselect_0.2.5                         
 [91] plyr_1.8.4                                magrittr_1.5                             
 [93] DESeq2_1.20.0                             R6_2.3.0                                 
 [95] IRanges_2.14.10                           Hmisc_4.1-1                              
 [97] TxDb.Dmelanogaster.UCSC.dm6.ensGene_3.4.1 DelayedArray_0.6.0                       
 [99] DBI_1.0.0                                 pillar_1.2.2                             
[101] foreign_0.8-71                            withr_2.1.2                              
[103] survival_2.43-3                           RCurl_1.95-4.11                          
[105] nnet_7.3-12                               tibble_1.4.2                             
[107] crayon_1.3.4                              progress_1.2.0                           
[109] usethis_1.4.0                             locfit_1.5-9.1                           
[111] grid_3.5.2                                data.table_1.11.4                        
[113] blob_1.1.1                                callr_3.1.1                              
[115] csaw_1.14.0                               digest_0.6.17                            
[117] xtable_1.8-2                              stats4_3.5.2                             
[119] munsell_0.4.3                             sessioninfo_1.1.1    ```
```
Thanks in advance.
Vivek

**Comment by hadley** [comment] 2019-07-21 12:55
Can you please have a go at creating a minimal reprex? Otherwise, I'm going to have to spend a lot of time working through your package to figure out where the problem is, and I'd rather spend that time fixing bugs.

**Comment by hadley** [comment] 2019-08-12 20:35
I've closed this issue due to lack of requested reprex. If you still care about this bug, please open a new issue with a reprex.

**Closed by hadley** 2019-08-12 20:35 UTC
Labels: reprex
