### ISSUE TITLE
If a.R file contain Chinese characters, after document(), a.Rd appear unreadable code

### ISSUE THREAD

**Issue by chuxinyuan** [r-lib/roxygen2#1120] opened 2020-06-19 06:28 UTC
I have developed a ecce package on gitlab, which can translate Chinese word into English, or English word into Chinese, so I need use Chinese character in code. 

R/a.R like this:
#' x = "苹果"

after devtools::document(), the man/a.Rd is:
x <- "鑻规灉"

**Comment by gaborcsardi** [comment] 2020-06-20 20:46
This is basically a duplicate of https://github.com/r-lib/roxygen2/issues/613 I think. 
See also the devtools issue linked from there: https://github.com/r-lib/devtools/issues/1421

The gist from "Writing R Extensions":
> Only ASCII characters (and the control characters tab, formfeed, LF and CR) should be used in code files. Other characters are accepted in comments14, but then the comments may not be readable in e.g. a UTF-8 locale. Non-ASCII characters in object names will normally15 fail when the package is installed. Any byte will be allowed in a quoted character string but ‘\uxxxx’ escapes should be used for non-ASCII characters. However, non-ASCII character strings may not be usable in some locales and may display incorrectly in others.

**Comment by chuxinyuan** [comment] 2020-06-20 21:19
Thank you for helping me find the root of the problem. 
I have developed a package,  Which translate  Chinese into English. 
But I can't get the qualified.RD file.
What a sad thing it is !!!

**Comment by gaborcsardi** [comment] 2020-06-20 21:26
I can take a look to see if we could make this work in comments. roxygen2 enforces UTF-8, so you would need to make sure that the files of your package are in UTF-8 and your `DESCRIPTION` also declares this in the `Encoding` field.

Can you point me to your package?

**Comment by chuxinyuan** [comment] 2020-06-20 21:53
ecce package is [here](https://gitlab.com/chuxinyuan/ecce)
I deleted some code in version 1.0.4 in R/.R file, such as `translate("苹果")`, then it works well.
But that's not enough to tell R user that it can translate Chinese into English.
You can try version 1.0.1, which is complete.

**Comment by chuxinyuan** [comment] 2020-06-20 22:29
This is not your problem, even if you change it here, it still won't pass when submitting CRAN.
This package is not on GitHub, I will upload it later.

**Closed** 2020-06-20 22:30 UTC

**Comment by gaborcsardi** [comment] 2020-06-20 22:59
Well, according to R-exts, you _may_ have non-ascii characters in comments, and that it all that roxygen2 needs to generate the Rd files. So I still want to make sure that roxygen2 is fine with this.

You are right that you'll have to switch to the `\uxxxx` notation in code, if you want to submit the package to CRAN, or if you want to make it portable.
