### ISSUE TITLE
@inheritParams separates parameters originally documented on the same line

### ISSUE THREAD

**Issue by mikkmart** [r-lib/roxygen2#1230] opened 2021-05-19 14:09 UTC
Consider for example:

```r
#' Foo
#' @inheritParams bar
foo <- function(a, b) a

#' Bar
#' @param a,b Parameters documented together.
bar <- function(a, b) b
```

This generates a single line of documentation for `a, b` in `?bar`, but two separate lines for `a` and `b` in `?foo` with the documentation text duplicated. Should the inherited lines in `?foo` match the original in `?bar`?

**Comment by hadley** [comment] 2022-03-29 18:53
Duplicate of #950

**Closed by hadley** 2022-03-29 18:53 UTC
