### ISSUE TITLE
`inheritParams`: Warning: Link to unknown topic in inherited text

### ISSUE THREAD

**Issue by romainfrancois** [r-lib/roxygen2#1283] opened 2022-02-02 12:59 UTC
When `document()`ing `dplyr` we're getting: 

```
Warning: Link to unknown topic in inherited text: dplyr::pull
Warning: Link to unknown topic in inherited text: dplyr::pull
```

probably because of `#' @inheritParams tidyselect::vars_pull`

[`?vars_pull`](https://github.com/r-lib/tidyselect/blob/main/R/vars-pull.R)  has: `#'   [quasiquotation][rlang::quasiquotation] (you can unquote column`

**Comment by hadley** [comment] 2022-04-06 11:51
Duplicate of #1135 (and now fixed)

**Closed by hadley** 2022-04-06 11:51 UTC
Labels: bug, inherit :family_man_woman_girl_boy:
