### ISSUE TITLE
Strange formatting for DOI when inheriting references from another package

### ISSUE THREAD

**Issue by Bisaloo** [r-lib/roxygen2#1177] opened 2020-12-07 13:23 UTC
I have a package 1 that has correctly formatted Rd files, with references:

https://github.com/cran/contactdata/blob/616fae9590a49d2464b95a25ee0fef82a7295497/man/contact_matrix.Rd#L28-L32

But when I try to inherit this reference (and other Rd sections) in another package 2 with

```r
#' @inherit contactdata::contact_matrix
```

it leads to a very strange output:

https://github.com/Bisaloo/NpiEurope_compendium/blob/52d88e0774e0eb8506e15c97509d16e2463f2e98/man/load_contact_data.Rd#L24-L28

**Comment by hadley** [comment] 2021-04-16 12:44
Hmmm, I think it's inlining what the `\doi` macro expands to.

**Comment by hadley** [comment] 2021-04-16 12:44
So I think it should still work, it just looks a bit weird?

**Comment by Bisaloo** [comment] 2021-04-16 13:23
No, you get warnings when you try to open the help file and the DOI doesn't appear.

I'm not sure how to produce a reprex in this case. Here's the best I could do:

``` r
usethis::create_package("inheritDOI", open = TRUE)
#> ✓ Creating 'inheritDOI/'
#> ✓ Setting active project to '/tmp/RtmpISvvZD/reprex-6b52484d438f-irate-booby/inheritDOI'
#> ✓ Creating 'R/'
#> ✓ Writing 'DESCRIPTION'
#> Package: inheritDOI
#> Title: What the Package Does (One Line, Title Case)
#> Version: 0.0.0.9000
#> Authors@R (parsed):
#>     * First Last <first.last@example.com> [aut, cre] (YOUR-ORCID-ID)
#> Description: What the package does (one paragraph).
#> License: `use_mit_license()`, `use_gpl3_license()` or friends to pick a
#>     license
#> Encoding: UTF-8
#> LazyData: true
#> Roxygen: list(markdown = TRUE)
#> RoxygenNote: 7.1.1.9001
#> ✓ Writing 'NAMESPACE'

usethis::use_r("test.R")
#> ● Edit 'R/test.R'
#> ● Call `use_test()` to create a matching test file

write(
  "#' Test DOI inheritance
  #' @inherit contactdata::contact_matrix references
  test <- function() { NULL }",
  file = "R/test.R"
)

roxygen2::roxygenise()
#> ℹ Loading inheritDOI
#> Writing test.Rd

(rd_contents <- scan("man/test.Rd", what = character(), sep = "\n"))
#>  [1] "% Generated by roxygen2: do not edit by hand"                                                                                                                                                                                                                                                                                                                             
#>  [2] "% Please edit documentation in R/test.R"                                                                                                                                                                                                                                                                                                                                  
#>  [3] "\\name{test}"                                                                                                                                                                                                                                                                                                                                                             
#>  [4] "\\alias{test}"                                                                                                                                                                                                                                                                                                                                                            
#>  [5] "\\title{Test DOI inheritance}"                                                                                                                                                                                                                                                                                                                                            
#>  [6] "\\usage{"                                                                                                                                                                                                                                                                                                                                                                 
#>  [7] "test()"                                                                                                                                                                                                                                                                                                                                                                   
#>  [8] "}"                                                                                                                                                                                                                                                                                                                                                                        
#>  [9] "\\description{"                                                                                                                                                                                                                                                                                                                                                           
#> [10] "Test DOI inheritance"                                                                                                                                                                                                                                                                                                                                                     
#> [11] "}"                                                                                                                                                                                                                                                                                                                                                                        
#> [12] "\\references{"                                                                                                                                                                                                                                                                                                                                                            
#> [13] "Kiesha Prem, Alex R. Cook, Mark Jit, Projecting social contact"                                                                                                                                                                                                                                                                                                           
#> [14] "matrices in 152 countries using contact surveys and demographic data, PLoS"                                                                                                                                                                                                                                                                                               
#> [15] "Comp. Biol. (2017), \\ifelse{{text}{doi: 10.1371/journal.pcbi.1005697 (URL: https://doi.org/10.1371/journal.pcbi.1005697)}{\\ifelse{{latex}{doi:\\out{\\\\nobreakspace{}}\\href{https://doi.org/10.1371/journal.pcbi.1005697}{10.1371\\out{\\\\slash{}}journal.pcbi.1005697}}{doi: \\href{https://doi.org/10.1371/journal.pcbi.1005697}{10.1371/journal.pcbi.1005697}}}}}"
#> [16] "}"

# Render relevant lines as HTML with rd2html() to emulate what happens when 
# the user runs ?test
pkgdown::rd2html(paste(rd_contents[13:15], collapse = "\n"))
#> Warning in tools::parse_Rd(con, fragment = fragment, encoding = "UTF-8"):
#> <connection>:3: unexpected '}', expecting TEXT or '{'
#> Warning in tools::parse_Rd(con, fragment = fragment, encoding = "UTF-8"): bad
#> markup (extra space?) at <connection>:3:352
#> Warning in tools::parse_Rd(con, fragment = fragment, encoding = "UTF-8"): <connection>:4: unexpected END_OF_INPUT '
#> ', expecting TEXT or '{'
#> [1] "Kiesha Prem, Alex R. Cook, Mark Jit, Projecting social contact"            
#> [2] "matrices in 152 countries using contact surveys and demographic data, PLoS"
#> [3] "Comp. Biol. (2017),"
```

<sup>Created on 2021-04-16 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0.9002)</sup>

**Comment by hadley** [comment] 2022-04-06 11:57
I think this is a duplicate of #1062

**Closed by hadley** 2022-04-06 11:57 UTC
Labels: feature, rd :writing_hand:

**Comment by Bisaloo** [comment] 2022-04-06 12:36
Yes, the reprex I posted earlier seems to be working fine now with the development version of roxygen2. Thanks!
