### ISSUE TITLE
`roxygenize()` generates wrong S3 exports if NAMESPACE doesn’t exist yet

### ISSUE THREAD

**Issue by jensmassberg** [r-lib/roxygen2#1407] opened 2022-07-20 13:06 UTC
`roxigenize()` generates the wrong exports for S3 methods with generic in other packages if the NAMESPACE file doesn't exist.
In my case I have the following function, implementing the `dplyr::tbl`generic:

```
#' @importFrom dplyr  tbl
#' @export
tbl.MyDBIConnection <- function(src, ...) { list() }
```

Running `roxygenize()` creates a NAMESPACE file with:

```
export(tbl.MyDBIConnection)
```

instead of 

```
S3method(tbl,MyDBIConnection)
```

Running `roxygenize()` a second time produces the correct NAMESPACE file.

Similar problems were reported in [r-lib/roxygen2/issues/372](https://github.com/r-lib/roxygen2/issues/372) and [r-lib/vctrs/issues/1362](https://github.com/r-lib/vctrs/issues/1362) and have been fixed in [eb7aa68](https://github.com/r-lib/roxygen2/commit/eb7aa68110d28c826d1a602fa43ae8c547d34925).

However, this seems to be broken again.

I suspect that this was broken by [97c6c2d](https://github.com/r-lib/roxygen2/commit/97c6c2d7eede09aa09bd72860304a483d7269005):

After this change first `load_code(...)` is called, then the preprocessing step performed where imports are added to the NAMESPACE file and then the second pass where the whole NAMESPACE file is written is performed.

As `load_code(...)` is performed before writing the initial NAMESPACE file with the imports, these imports aren't loaded into env and thus the imported generics aren't found.

# How to reproduce

(similar to [r-lib/vctrs/issues/1362](https://github.com/r-lib/vctrs/issues/1362))

1. Generate an empty package using `Rscript -e 'dummy = 1; package.skeleton("foo", "dummy")'`

2. `cd foo`

3. Add imports: `echo 'Imports: roxygen2' >> DESCRIPTION`

4. `rm NAMESPACE`

5. Add a new file R/test.r with the contents
```
#' @importFrom dplyr  tbl
#' @export
tbl.MyDBIConnection <- function(src, ...) { list() }
```

6. Run `Rscript -e 'roxygen2::roxygenize()'`

# Output:
```
# Generated by roxygen2: do not edit by hand

export(tbl.MyDBIConnection)
importFrom(dplyr,tbl)
```

# Expected output:
```
# Generated by roxygen2: do not edit by hand

S3method(tbl,MyDBIConnection)
importFrom(dplyr,tbl)
```

**Comment by hadley** [comment] 2022-07-21 21:55
Probably a duplicate of #1144

**Closed** 2023-11-02 12:49 UTC
