### ISSUE TITLE
Release roxygen2 7.2.0

### ISSUE THREAD

**Issue by hadley** [r-lib/roxygen2#1336] opened 2022-04-25 14:08 UTC
Prepare for release:

* [x] `git pull`
* [x] Check [current CRAN check results](https://cran.rstudio.org/web/checks/check_results_roxygen2.html)
* [x] [Polish NEWS](https://style.tidyverse.org/news.html#news-release)
* [x] `urlchecker::url_check()`
* [x] `devtools::check(remote = TRUE, manual = TRUE)`
* [x] `devtools::check_win_devel()`
* [x] Review pkgdown reference index for, e.g., missing topics
* [x] Draft blog post — https://github.com/tidyverse/tidyverse.org/pull/577
* [x] `revdepcheck::cloud_check()`
  * [x] https://github.com/ThinkR-open/attachment/issues/48
  * [x] https://github.com/ropensci/DataPackageR/issues/98
  * [x] https://github.com/zhuxr11/roclang/issues/1
  * [x] https://github.com/torfason/zmisc/issues/1
* [x] Wait until May 13
* [x] Update `cran-comments.md`
* [x] `git push`
* [x] Slack link to draft blog in #open-source-comms

Submit to CRAN:

* [x] `usethis::use_version('minor')`
* [x] `devtools::submit_cran()`
* [x] Approve email

Wait for CRAN...

* [x] Accepted :tada:
* [x] `git push`
* [x] `usethis::use_github_release()`
* [x] `usethis::use_dev_version()`
* [x] `git push`
* [x] Finish blog post
* [x] Tweet
* [x] Add link to blog post in pkgdown news menu

**Comment by zeehio** [comment] 2022-05-02 18:15
Is there any chance of getting #1343 merged before the upcoming release? Or is the release process already too advanced?

I am hitting that bug on the upcoming version of a Bioconductor package I maintain and it would be nice to avoid depending on dev versions if possible.

**Comment by hadley** [comment] 2022-05-02 22:59
@zeehio maaaaaybe. The problem is that I have to load up the argument wrapping code up into my head to assess the potential risks of the change. So while the change itself is fairly simple, I have to spend a decent amount of time to remember how it all works. I'll do it if I can, but I can't promise anything.

**Comment by zeehio** [comment] 2022-05-03 04:34
Thanks! I can't imagine how busy you may be.

Don't sweat it. For now I have removed the non-breaking space (nbsp) from my default value in my package. That may lead to weird captions in plots (where line breaks are introduced at bad places due to the missing nbsp) but I can avoid check warnings caused by this issue. I can live with that for some months if I have to.

**Comment by hadley** [comment] 2022-05-03 12:07
@zeehio you could also use a manual `@usage`, I think

**Closed** 2022-05-13 20:22 UTC
